version: '3.9'

services:
  db:
    container_name: rns_trial_task_db
    platform: linux/amd64
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=rns_trial_task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rns_trial_task:
    platform: linux/amd64
    build: .
    command: python manage.py runserver 0.0.0.0:8013
    container_name: rns_trial_task
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rns_trial_task_db
    volumes:
      - .:/code
    ports:
      - "8013:8013"
    depends_on:
      - db
